import type {
  Settings,
  StoreData,
} from "./types";
import {
  SEED_PRODUCTS,
  SEED_CATEGORIES,
  SEED_BRANDS,
  SEED_ORDERS,
  SEED_COUPONS,
  SEED_ARTICLES,
  SEED_CUSTOMERS,
  SEED_SUPPLIERS,
  SEED_PAYMENT_GATEWAYS,
  SEED_POPUPS,
  SEED_AFFILIATES,
  SEED_LOYALTY_TIERS,
  SEED_LIVE_SALES,
  SEED_REDIRECTS,
  SEED_RETURNS,
} from "./seed-data";

export const STORE_VERSION = 11;

/* ------------------------------- Settings ------------------------------ */
export const SEED_SETTINGS: Settings = {
  storeName: "ALAYA INSIDER",
  storeShort: "ALAYA",
  tagline: "Premium Editorial Shopping — Curated by Experts",
  description: "ALAYA INSIDER discovers and curates the finest products from around the world. From artisanal home goods to clean beauty essentials, every piece is selected for its quality, craftsmanship, and story.",
  defaultTheme: "light",
  defaultLanguage: "en",
  accentLight: "#9c7a4b",
  accentDark: "#c9a876",
  currency: { code: "USD", symbol: "$", rate: 1 },
  announcement: {
    enabled: true,
    text: "Free shipping on orders over $150 | Use code INSIDER15 for 15% off orders $200+",
    link: "/shop",
  },
  announcements: [],
  heroSlides: [
    { id: "hero_spring", eyebrow: "Spring 2026 Collection", title: "A Fresh Chapter in", highlight: "Thoughtful Living", description: "Discover our curated Spring Collection — where clean lines meet warm textures, and every piece tells a story of artisanal craftsmanship.", image: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=900", ctaLabel: "Shop the Collection", ctaLink: "/shop", cta2Label: "Read Our Journal", cta2Link: "/journal", align: "left" },
    { id: "hero_beauty", eyebrow: "Clean Beauty Edit", title: "Radiant Skin", highlight: "Starts Here", description: "Our clean beauty collection harnesses the power of active ingredients — formulated without compromise, for results you can see and feel.", image: "https://images.pexels.com/photos/3738343/pexels-photo-3738343.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=900", ctaLabel: "Explore Beauty", ctaLink: "/shop?category=beauty", align: "right" },
    { id: "hero_travel", eyebrow: "Weekend Escape", title: "Pack Light,", highlight: "Travel Far", description: "From cabin-ready luggage to smart organizers — everything you need for effortless travel, designed for the modern journey.", image: "https://images.pexels.com/photos/1008155/pexels-photo-1008155.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=900", ctaLabel: "Shop Travel", ctaLink: "/shop?category=travel", align: "center" },
  ],
  homeSections: [
    { id: "sec_hero", label: "Hero Slider", enabled: true },
    { id: "sec_featured", label: "Featured Products", enabled: true },
    { id: "sec_categories", label: "Shop by Category", enabled: true },
    { id: "sec_bestsellers", label: "Best Sellers", enabled: true },
    { id: "sec_editorial", label: "Editorial Picks", enabled: true },
    { id: "sec_journal", label: "From the Journal", enabled: true },
    { id: "sec_newsletter", label: "Newsletter Signup", enabled: true },
  ],
  design: {
    primary: "#211c15",
    secondary: "#6e6356",
    accent: "#9c7a4b",
    success: "#4b7a52",
    warning: "#b9802f",
    danger: "#b14b46",
    info: "#4f6da3",
    fontHeading: "Playfair Display",
    fontBody: "Inter",
    radiusSm: 8,
    radiusMd: 14,
    radiusLg: 20,
    shadowSoft: true,
    animationSpeed: "normal",
  },
  header: {
    sticky: true, transparent: true, showAnnouncement: true, showMegaMenu: true,
    showSearch: true, showWishlist: true, showCompare: true, showNotifications: true,
    showAccount: true, showDarkMode: true, showLanguage: true, showCurrency: true,
  },
  footer: {
    showNewsletter: true, showSocial: true, showPolicies: true,
    showPayments: true, showTrustBadges: true, showAffiliateDisclosure: true,
  },
  shipping: { freeOver: 150, flatRate: 12 },
  taxRate: 0.08,
  contactEmail: "hello@alayainsider.com",
  supportEmail: "support@alayainsider.com",
  contactPhone: "+1 (212) 555-0198",
  address: "200 Park Avenue South, Suite 1500, New York, NY 10003",
  social: {
    instagram: "https://instagram.com/alayainsider",
    pinterest: "https://pinterest.com/alayainsider",
    tiktok: "https://tiktok.com/@alayainsider",
    youtube: "https://youtube.com/@alayainsider",
    x: "https://x.com/alayainsider",
  },
  seo: {
    title: "ALAYA INSIDER — Premium Editorial Shopping | Curated Home, Beauty & Lifestyle",
    description: "Discover the finest curated products from around the world. Artisanal home goods, clean beauty, premium kitchen tools, and intentional lifestyle essentials — all selected by our experts.",
    keywords: "premium shopping, curated products, home decor, beauty products, kitchen tools, lifestyle goods, artisan, editorial shopping, ALAYA INSIDER",
    ogImage: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1200&h=630",
    twitterHandle: "@alayainsider",
  },
  features: {
    wishlist: true, compare: true, recentlyViewed: true, darkMode: true,
    affiliate: true, reviews: true, digital: true, coupons: true,
    brands: true, journal: true, accounts: true, multiLanguage: true,
  },
  adminEmail: "alayainsider@gmail.com",
  adminPhone: "+91 8431364706",
  adminPassword: "Alaya@1923",
  mfaMethod: "email_sms",
  totpSecret: "",
  totpVerified: false,
  totpBackupCodes: [],
};

export const SEED_STORE: StoreData = {
  version: STORE_VERSION,
  products: SEED_PRODUCTS,
  categories: SEED_CATEGORIES,
  brands: SEED_BRANDS,
  orders: SEED_ORDERS,
  coupons: SEED_COUPONS,
  articles: SEED_ARTICLES,
  customers: SEED_CUSTOMERS,
  suppliers: SEED_SUPPLIERS,
  paymentGateways: SEED_PAYMENT_GATEWAYS,
  popups: SEED_POPUPS,
  affiliates: SEED_AFFILIATES,
  loyaltyTiers: SEED_LOYALTY_TIERS,
  liveSales: SEED_LIVE_SALES,
  redirects: SEED_REDIRECTS,
  returns: SEED_RETURNS,
  questions: [],
  abandonedCarts: [],
  referrals: [],
  supportTickets: [],
  auditLogs: [],
  settings: SEED_SETTINGS,
};
