/**
 * ALAYA INSIDER — Seed Data Index
 * Combines all seed data modules into the main seed function.
 * Used by server/src/db.ts to populate the database on first launch.
 */

import { v4 } from "uuid";
import { img, wide, daysAgo, hoursAgo } from "./helpers.js";
import { SEED_CATEGORIES } from "./categories.js";
import { SEED_BRANDS } from "./categories.js";
import { SEED_PRODUCTS } from "./products.js";
import { SEED_CUSTOMERS } from "./users.js";
import {
  SEED_ARTICLES, SEED_COUPONS, SEED_AFFILIATES, SEED_SUPPLIERS,
  SEED_ORDERS, SEED_RETURNS, SEED_POPUPS, SEED_LOYALTY_TIERS,
  SEED_LIVE_SALES, SEED_SETTINGS_EXTRA, SEED_HERO_SLIDES,
} from "./content.js";

import type { StoreData, Product } from "../db.js";

/** Generate a timestamp-based prefixed ID */
function genId(prefix = "id"): string {
  return `${prefix}_${v4().slice(0, 8)}${Date.now().toString(36).slice(-4)}`;
}

/** Generate an order number */
function ono(): string {
  return `AL-${Math.floor(100000 + Math.random() * 900000)}`;
}

/** Convert seed product to db Product type */
function toDbProduct(sp: typeof SEED_PRODUCTS[0]): Product {
  return {
    id: sp.id,
    slug: sp.slug,
    name: sp.name,
    brand: sp.brand,
    brandId: sp.brandId,
    category: sp.category,
    type: sp.type,
    price: sp.price,
    salePrice: sp.salePrice,
    rating: sp.rating,
    reviewCount: sp.reviewCount,
    images: sp.images.map((url: string) => `${url}?auto=compress&cs=tinysrgb&fit=crop&w=800&h=1200`),
    shortDescription: sp.shortDescription,
    description: sp.description,
    features: sp.features,
    variants: sp.variants,
    stock: sp.stock,
    sku: sp.sku,
    tags: sp.tags,
    barcode: sp.barcode,
    gtin: sp.gtin,
    asin: sp.asin,
    supplierId: sp.supplierId,
    costPrice: sp.costPrice,
    affiliate: sp.affiliate,
    affiliateUrl: sp.affiliateUrl,
    affiliatePartner: sp.affiliatePartner,
    affiliateNetwork: sp.affiliateNetwork,
    affiliateCommission: sp.affiliateCommission,
    featured: sp.featured,
    bestSeller: sp.bestSeller,
    isNew: sp.isNew,
    comingSoon: sp.comingSoon,
    preorder: sp.preorder,
    status: sp.status || "published",
    reviews: sp.reviews.map((r) => ({
      id: r.id,
      author: r.author,
      rating: r.rating,
      title: r.title,
      body: r.body,
      date: r.date,
      verified: r.verified,
      helpful: r.helpful,
      pinned: r.pinned,
    })),
    specs: sp.specs,
    createdAt: sp.createdAt,
  };
}

/**
 * Create the full seed data store with all realistic demo data.
 * Returns a StoreData object ready for use by the db module.
 */
export function createSeedData(): StoreData {
  const products = SEED_PRODUCTS.map(toDbProduct);

  return {
    version: 11,
    products,
    categories: SEED_CATEGORIES.map((c) => ({
      id: c.id,
      name: c.name,
      tagline: c.tagline,
      description: c.description,
      image: c.image,
    })),
    brands: SEED_BRANDS.map((b) => ({
      id: b.id,
      name: b.name,
      slug: b.slug,
      tagline: b.tagline,
      description: b.description,
      image: b.image,
      logo: b.logo,
      website: b.website,
      instagram: b.instagram,
      country: b.country,
      featured: b.featured,
    })),
    orders: SEED_ORDERS.map((o) => ({
      id: o.id,
      number: o.number,
      items: o.items.map((i) => ({
        productId: i.productId,
        name: i.name,
        image: i.image,
        price: i.price,
        qty: i.qty,
      })),
      subtotal: o.subtotal,
      discount: o.discount,
      shipping: o.shipping,
      tax: o.tax,
      total: o.total,
      currency: o.currency,
      couponCode: o.couponCode,
      paymentMethod: o.paymentMethod,
      trackingNumber: o.trackingNumber || undefined,
      courier: o.courier || undefined,
      customer: {
        name: o.customer.name,
        email: o.customer.email,
        address: o.customer.address,
        city: o.customer.city,
        country: o.customer.country,
        zip: o.customer.zip,
      },
      status: o.status,
      createdAt: o.createdAt,
    })),
    coupons: SEED_COUPONS.map((c) => ({
      id: c.id,
      code: c.code,
      type: c.type,
      value: c.value,
      minSpend: c.minSpend,
      active: c.active,
      description: c.description,
      expiresAt: c.expiresAt,
      usageLimit: c.usageLimit,
      usedCount: c.usedCount,
    })),
    articles: SEED_ARTICLES.map((a) => ({
      id: a.id,
      slug: a.slug,
      title: a.title,
      excerpt: a.excerpt,
      body: a.body,
      cover: a.cover,
      author: a.author,
      authorRole: a.authorRole,
      category: a.category,
      tags: a.tags,
      readMinutes: a.readMinutes,
      publishedAt: a.publishedAt,
      featured: a.featured,
    })),
    customers: SEED_CUSTOMERS.map((c) => ({
      id: c.id,
      name: c.name,
      email: c.email,
      password: c.password,
      phone: c.phone,
      country: c.country,
      createdAt: c.createdAt,
      lastLogin: c.lastLogin,
      status: c.status,
      addresses: c.addresses.map((a) => ({
        id: a.id,
        label: a.label,
        name: a.name,
        line1: a.line1,
        city: a.city,
        country: a.country,
        zip: a.zip,
        phone: a.phone,
      })),
      newsletter: c.newsletter,
      timeline: c.timeline.map((t) => ({
        id: t.id,
        type: t.type,
        label: t.label,
        ts: t.ts,
        meta: t.meta,
      })),
      notes: c.notes.map((n) => ({
        id: n.id,
        author: n.author,
        body: n.body,
        pinned: n.pinned,
        private: false,
        ts: n.ts,
      })),
      tasks: c.tasks.map((t) => ({
        id: t.id,
        title: t.title,
        type: t.type,
        assignee: t.assignee,
        dueDate: t.dueDate,
        priority: t.priority,
        done: t.done,
        ts: t.ts,
      })),
      preferences: c.preferences,
      loyaltyPoints: c.loyaltyPoints,
      storeCredit: c.storeCredit,
      referralCode: c.referralCode,
    })),
    questions: [],
    suppliers: SEED_SUPPLIERS.map((s) => ({
      id: s.id,
      name: s.name,
      email: s.email,
      country: s.country,
      priority: s.priority,
      active: s.active,
      handlingDays: s.handlingDays,
      notes: s.notes,
    })),
    paymentGateways: [
      { id: genId("gw"), name: "Stripe", code: "stripe", mode: "live", active: true, countries: [] },
      { id: genId("gw"), name: "PayPal", code: "paypal", mode: "live", active: true, countries: [] },
      { id: genId("gw"), name: "Apple Pay", code: "applepay", mode: "live", active: true, countries: ["United States", "United Kingdom", "Canada"] },
      { id: genId("gw"), name: "Google Pay", code: "googlepay", mode: "live", active: true, countries: ["United States", "United Kingdom", "India"] },
      { id: genId("gw"), name: "Razorpay (UPI)", code: "razorpay", mode: "live", active: true, countries: ["India"] },
    ],
    returns: SEED_RETURNS.map((r) => ({
      id: r.id,
      number: r.number,
      orderId: r.orderId,
      orderNumber: r.orderNumber,
      customer: { name: r.customer.name, email: r.customer.email },
      type: r.type,
      reason: r.reason,
      comment: r.comment,
      status: r.status,
      refundAmount: r.refundAmount,
      createdAt: r.createdAt,
    })),
    redirects: [
      { id: genId("redir"), from: "/shop/spring-collection", to: "/shop?tag=spring", type: 301, active: true, hits: 245, createdAt: daysAgo(120) },
      { id: genId("redir"), from: "/old-blog", to: "/journal", type: 301, active: true, hits: 89, createdAt: daysAgo(180) },
    ],
    popups: SEED_POPUPS.map((p) => ({
      id: p.id,
      name: p.name,
      type: p.type,
      trigger: p.trigger,
      headline: p.headline,
      body: p.body,
      ctaLabel: p.ctaLabel,
      ctaLink: p.ctaLink,
      couponCode: p.couponCode,
      triggerValue: p.triggerValue,
      active: p.active,
      views: p.views,
      conversions: p.conversions,
    })),
    abandonedCarts: [],
    referrals: [
      { id: genId("ref"), code: "ALAYA-ISABELLA", customerName: "Isabella Moreau", clicks: 12, signups: 3, purchases: 2, rewardEarned: 45 },
      { id: genId("ref"), code: "ALAYA-ELEANOR", customerName: "Eleanor Whitfield", clicks: 46, signups: 8, purchases: 5, rewardEarned: 120 },
    ],
    loyaltyTiers: SEED_LOYALTY_TIERS.map((t) => ({
      id: t.id,
      name: t.name,
      minPoints: t.minPoints,
      perk: t.perk,
    })),
    liveSales: SEED_LIVE_SALES.map((s) => ({
      id: s.id,
      customerName: s.customerName,
      city: s.city,
      country: s.country,
      productId: s.productId,
      minutesAgo: s.minutesAgo,
    })),
    supportTickets: [],
    affiliates: SEED_AFFILIATES.map((a) => ({
      id: a.id,
      name: a.name,
      url: a.url,
      commission: a.commission,
      active: a.active,
    })),
    auditLogs: [],
    settings: {
      storeName: "ALAYA INSIDER",
      storeShort: "ALAYA",
      tagline: SEED_SETTINGS_EXTRA.tagline,
      description: SEED_SETTINGS_EXTRA.description,
      defaultTheme: "light",
      defaultLanguage: "en",
      accentLight: "#9c7a4b",
      accentDark: "#c9a876",
      currency: { code: "USD", symbol: "$", rate: 1 },
      announcement: { enabled: true, text: "Free shipping on orders over $150 | Use code INSIDER15 for 15% off orders $200+", link: "/shop" },
      announcements: [],
      heroSlides: SEED_HERO_SLIDES.map((hs) => ({
        id: hs.id,
        eyebrow: hs.eyebrow,
        title: hs.title,
        highlight: hs.highlight,
        description: hs.description,
        image: hs.image,
        ctaLabel: hs.ctaLabel,
        ctaLink: hs.ctaLink,
        cta2Label: hs.cta2Label,
        cta2Link: hs.cta2Link,
        align: hs.align,
      })),
      homeSections: [
        { id: "sec_hero", label: "Hero Slider", enabled: true },
        { id: "sec_featured", label: "Featured Products", enabled: true },
        { id: "sec_categories", label: "Shop by Category", enabled: true },
        { id: "sec_bestsellers", label: "Best Sellers", enabled: true },
        { id: "sec_editorial", label: "Editorial Picks", enabled: true },
        { id: "sec_journal", label: "From the Journal", enabled: true },
        { id: "sec_newsletter", label: "Newsletter Signup", enabled: true },
      ],
      design: {
        primary: "#211c15",
        secondary: "#6e6356",
        accent: "#9c7a4b",
        success: "#4b7a52",
        warning: "#b9802f",
        danger: "#b14b46",
        info: "#4f6da3",
        fontHeading: "Playfair Display",
        fontBody: "Inter",
        radiusSm: 8,
        radiusMd: 14,
        radiusLg: 20,
        shadowSoft: true,
        animationSpeed: "normal",
      },
      header: {
        sticky: true, transparent: true, showAnnouncement: true, showMegaMenu: true,
        showSearch: true, showWishlist: true, showCompare: true, showNotifications: true,
        showAccount: true, showDarkMode: true, showLanguage: true, showCurrency: true,
      },
      footer: {
        showNewsletter: true, showSocial: true, showPolicies: true,
        showPayments: true, showTrustBadges: true, showAffiliateDisclosure: true,
      },
      shipping: { freeOver: 150, flatRate: 12 },
      taxRate: 0.08,
      contactEmail: SEED_SETTINGS_EXTRA.contactEmail,
      supportEmail: SEED_SETTINGS_EXTRA.supportEmail,
      contactPhone: SEED_SETTINGS_EXTRA.contactPhone,
      adminEmail: "alayainsider@gmail.com",
      adminPhone: "+91 8431364706",
      mfaMethod: "email_sms",
      totpSecret: "",
      totpVerified: false,
      totpBackupCodes: [],
      address: SEED_SETTINGS_EXTRA.address,
      social: SEED_SETTINGS_EXTRA.social,
      seo: SEED_SETTINGS_EXTRA.seo,
      features: {
        wishlist: true, compare: true, recentlyViewed: true, darkMode: true,
        affiliate: true, reviews: true, digital: true, coupons: true,
        brands: true, journal: true, accounts: true, multiLanguage: true,
      },
      adminPassword: SEED_SETTINGS_EXTRA.adminPassword,
    },
  };
}
